API Crear un nuevo plan semanal por usario terminado
ginamerla/dietapp pull request #18
Opened 2020-04-14 16:40 UTC by ginamerla

Feature de crear un nuevo WeeklyPlan para un usuario terminado

2020-04-14 16:50 UTC, ginamerla commented
Backup de la base de datos actualizada

2020-04-17 01:14 UTC, vampymcr23 requested changes
Review inicial. Revisa los comments.

2020-04-17 01:14 UTC, vampymcr23 commented on src/main/java/com/tortu/api/daos/impl/DietaUsuarioDaoImpl.java
> +        LOG.info(String.format("Eliminando DIETA_USUARIO: %d", id));
Este lo puedes hacer asi:
LOG.info("Eliminando DIETA_USUARIO: {}", id);

2020-04-17 01:14 UTC, vampymcr23 commented on src/main/java/com/tortu/api/daos/impl/DietaUsuarioDaoImpl.java
> +        LOG.info(String.format("Consultando lista de ids del usuario: %d", userId));
Igual que el comentario de arriba.

2020-04-17 01:14 UTC, vampymcr23 commented on src/main/java/com/tortu/api/models/DayEnum.java
> +
Java doc

2020-04-17 01:14 UTC, vampymcr23 commented on src/main/java/com/tortu/api/rest/restservices/WeeklyPlanRestService.java
> +        return Response.ok().build();
Este solo regresa un 200 OK ?

2020-04-17 01:14 UTC, vampymcr23 commented on src/main/java/com/tortu/api/services/impl/WeeklyPlanServiceImpl.java
> +            if(periodId==1){//desayuno
Tienes que tener cuidado que cuando hagas la tabla de Periodo, que estos ids no sean auto_increment en la base de datos, sino esta logica se rompera.
Crea una constante para cada numero, algo asi como:
private static final int BREAKFAST_MEAL_PERIOD_ID = 1;

2020-04-17 19:38 UTC, ginamerla commented on src/main/java/com/tortu/api/rest/restservices/WeeklyPlanRestService.java
> +        return Response.ok().build();
pues por lo pronto si, que mas puede devolver?

2020-04-19 17:50 UTC, vampymcr23 requested changes
Se te fue un error en la asignacion de los ids en las constantes.

2020-04-19 17:50 UTC, vampymcr23 commented on src/main/java/com/tortu/api/services/impl/WeeklyPlanServiceImpl.java
> +    private static final int LUNCH_MEAL_PERIOD_ID = 1;
Los ids deben ser diferentes, sino nada mas va a entrar al primer if y luego los demas no.

2020-04-22 15:20 UTC, merged