api CategoriaIngrediente, Receta, Usuario, Ingrediente, DietaUsuario,…
ginamerla/dietapp pull request #8
Opened 2019-09-30 21:22 UTC by ginamerla

… UsuarioLayout y LayoutPeriodo

2019-10-01 01:00 UTC, vampymcr23 requested changes
Muy bien mi tortuguita!  solo falta agregar unos logs  y unas sugerencias que te puse por ahi. Que no se te olviden los java doc (comentarios).

2019-10-01 01:00 UTC, vampymcr23 commented on src/main/java/com/tortu/api/daos/impl/DietaUsuarioDaoImpl.java
> +    JdbcTemplate jdbcTemplate;
si este jdbc template no sera compartido, ponlo como privado.

2019-10-01 01:00 UTC, vampymcr23 commented on src/main/java/com/tortu/api/daos/impl/DietaUsuarioDaoImpl.java
> +        if(updatedRows==0){
Logs! necesitas logear que paso. La excepcion solo funciona en el request que te mandaron pero no se registra en ningun lado, para eso necesitarias logear un LOG.warn o LOG.error

2019-10-01 01:00 UTC, vampymcr23 commented on src/main/java/com/tortu/api/daos/impl/IngredienteDaoImpl.java
> +    JdbcTemplate jdbcTemplate;
privado

2019-10-01 01:00 UTC, vampymcr23 commented on src/main/java/com/tortu/api/daos/impl/IngredienteDaoImpl.java
> +            throw  new GeneralException("El INGREDIENTE no pudo ser guardado");
logs!

2019-10-01 01:00 UTC, vampymcr23 commented on src/main/java/com/tortu/api/daos/impl/IngredienteDaoImpl.java
> +            throw  new GeneralException("El INGREDIENTE no pudo ser actualizado");
logs

2019-10-01 01:00 UTC, vampymcr23 commented on src/main/java/com/tortu/api/daos/impl/IngredienteDaoImpl.java
> +            throw  new GeneralException("El INGREDIENTE no pudo ser eliminado");
aqui tambien faltan logs

2019-10-01 01:00 UTC, vampymcr23 commented on src/main/java/com/tortu/api/daos/impl/IngredienteDaoImpl.java
> +        LOG.info(String.format("Consultando INGREDIENTE con id: %d",id));
otra forma de logear mensajes es:
`
LOG.info("Consultando INGREDIENTE con id: {}", id);
`
Asi no necesitas usar el String.format

2019-10-01 01:00 UTC, vampymcr23 commented on src/main/java/com/tortu/api/daos/impl/LayoutPeriodoDaoImpl.java
> +    private JdbcTemplate jdbcTemplate;
👍

2019-10-01 01:00 UTC, vampymcr23 commented on src/main/java/com/tortu/api/daos/impl/LayoutPeriodoDaoImpl.java
> +            throw new GeneralException("No se pudo insertar el nuevo regitro LayoutPeriodo");
logs

2019-10-01 01:00 UTC, vampymcr23 commented on src/main/java/com/tortu/api/daos/impl/RecetaDaoImpl.java
> +            throw  new GeneralException("La RECETA no pudo ser guardada");
logs

2019-10-01 01:00 UTC, vampymcr23 commented on src/main/java/com/tortu/api/daos/impl/UsuarioDaoImpl.java
> +            throw  new GeneralException("El USUARIO no pudo ser guardado");
logs

2019-10-01 01:00 UTC, vampymcr23 commented on src/main/java/com/tortu/api/daos/impl/UsuarioDaoImpl.java
> +            throw  new GeneralException("El USUARIO no pudo ser actualizado");
aqui tambien faltan logs

2019-10-01 01:00 UTC, vampymcr23 commented on src/main/java/com/tortu/api/daos/impl/UsuarioLayoutDaoImpl.java
> +    public static final Logger LOG = LoggerFactory.getLogger(UsuarioDaoImpl.class);
aqui estas poniendo la clase incorrecta, deberia de ser `UsuarioLayoutDaoImpl.class`

2019-10-01 01:00 UTC, vampymcr23 commented on src/main/java/com/tortu/api/daos/impl/UsuarioLayoutDaoImpl.java
> +    JdbcTemplate jdbcTemplate;
👎

2019-10-01 01:00 UTC, vampymcr23 commented on src/main/java/com/tortu/api/daos/impl/UsuarioLayoutDaoImpl.java
> +            throw  new GeneralException("El USUARIO_LAYOUT no pudo ser guardado");
logs

2019-10-01 01:00 UTC, vampymcr23 commented on src/main/java/com/tortu/api/rest/mappers/IngredienteResourceMapper.java
> +
Java doc

2019-10-01 01:00 UTC, vampymcr23 commented on src/main/java/com/tortu/api/rest/restservices/DietaUsuarioRestService.java
> +        DietaUsuarioResource resource = resourceMapper.map(dietaUsuario);
Te falto aqui:
`
if(dietaUsuario == null) {
   //codigo para regresar un error 404 - Not found
}
`

2019-10-01 01:00 UTC, vampymcr23 commented on src/main/java/com/tortu/api/rest/restservices/IngredienteRestService.java
> +    @Autowired
De preferencia agrega el Qualifier aqui tambien. Puede que spring inyecte el bean incorrecto

2019-10-01 01:00 UTC, vampymcr23 commented on src/main/java/com/tortu/api/rest/restservices/LayoutPeriodoRestService.java
> +        LayoutPeriodoResource resource = resourceMapper.map(layoutPeriodo);
Aqui tambien, regresar un 404 si no se encontro nada con ese id (si layoutPeriodo es nulo)

2019-10-01 01:00 UTC, vampymcr23 commented on src/main/java/com/tortu/api/rest/validators/dietausuarioapi/CreateDietaUsuarioValidatorImpl.java
> +            throw new GeneralException("El ID de la dieta_usuario es nulo");
El mensaje deberia de decir el id del usuario es nulo.

2019-10-01 01:00 UTC, vampymcr23 commented on src/main/java/com/tortu/api/rest/validators/dietausuarioapi/CreateDietaUsuarioValidatorImpl.java
> +
Java doc

2019-10-01 01:00 UTC, vampymcr23 commented on src/main/java/com/tortu/api/rest/validators/dietausuarioapi/UpdateDietaUsuarioValidatorImpl.java
> +
Java doc

2019-10-01 01:00 UTC, vampymcr23 commented on src/main/java/com/tortu/api/rest/validators/dietausuarioapi/UpdateDietaUsuarioValidatorImpl.java
> +      * @param modelo
que representa "modelo" aqui? necesitas poner mas informacion despues de "@param modelo ".
Tambien en el @throws GeneralException, necesitas decir cuando se lanza la excepcion.

2019-10-01 01:00 UTC, vampymcr23 commented on src/main/java/com/tortu/api/rest/validators/ingredientesapi/CreateIngredienteValidatorImpl.java
> +
Java Doc

2019-10-01 01:00 UTC, vampymcr23 commented on src/main/java/com/tortu/api/rest/validators/ingredientesapi/UpdateIngredienteValidatorImpl.java
> +
Java Doc

2019-10-01 01:00 UTC, vampymcr23 commented on src/main/java/com/tortu/api/rest/validators/layoutperiodoapi/CreateLayoutPeriodoValidatorImpl.java
> + * Implementacion del validador para crear un nuevo layoutPeriodo
👍

2019-10-01 01:00 UTC, vampymcr23 commented on src/main/java/com/tortu/api/rest/validators/layoutperiodoapi/UpdateLayoutPeriodoValidatorImpl.java
> + * Implmentacion del validador para actualizar un LayoutPeriodo
💯

2019-10-01 01:00 UTC, vampymcr23 commented on src/main/java/com/tortu/api/rest/validators/usuariolayoutapi/CreateUsuarioLayoutValidatorImpl.java
> + * Valida los datos de UsuarioLayout para crear uno nuevo
👍

2019-10-01 01:00 UTC, vampymcr23 commented on src/main/java/com/tortu/api/rest/validators/usuariolayoutapi/UpdateUsuarioLayoutValidatorImpl.java
> + * Valida los campos para actualizar un UsuarioLayout
👍

2019-10-01 01:00 UTC, vampymcr23 commented on src/main/java/com/tortu/api/services/DietaUsuarioService.java
> + * Interface de los servicios para Dieta_Usuario
Muy bien documentado quesito! 🥇

2019-10-01 01:00 UTC, vampymcr23 commented on src/main/java/com/tortu/api/services/IngredienteService.java
> + * Interface para el servicio de Ingrediente
Muy bien documentado 🥇

2019-10-01 01:00 UTC, vampymcr23 commented on src/main/java/com/tortu/api/services/LayoutPeriodoService.java
> + * Interface para los servicios de LayoutPeriodo
Muy bien documentado 🥇

2019-10-01 01:00 UTC, vampymcr23 commented on src/main/java/com/tortu/api/services/UsuarioLayoutService.java
> + * Interface de los servicios de UsuarioLayout
Muy bien documentado 🥇

2019-10-01 01:00 UTC, vampymcr23 commented on src/main/java/com/tortu/api/services/impl/IngredienteServiceImpl.java
> +
Este espacio no va :)

2019-10-01 01:00 UTC, vampymcr23 commented on src/main/java/com/tortu/api/services/impl/LayoutPeriodoServiceImpl.java
> +            throw new GeneralException("El LayoutPeriodo no fue encontrado");
👍  aqui si lo hiciste, si no encontro nada entonces lanza una excepcion.

2019-10-01 01:00 UTC, vampymcr23 commented on src/test/java/com/tortu/api/rest/mappers/DietaUsuarioResourceMapperTest.java
> +        assertEquals(dietaUsuario.getIdDietaUsuario(), dietaUsuarioResource.getIdDietaUsuario());
👍

2019-10-01 01:00 UTC, vampymcr23 commented on src/test/java/com/tortu/api/rest/mappers/LayoutPeriodoResourceMapperTest.java
> +        layoutPeriodo.setIdLayout(1);
Sugerencia: trata de usar siempre diferentes valores, por que esto puede ocultar un problema de mapping en tu codigo. Si tu implementacion esta copiando un valor en una propiedad incorrecta y siempre usas los mismos valores, aunque tu test pase, no vas a cachar el problema.

2019-10-01 01:00 UTC, vampymcr23 commented on src/test/java/com/tortu/api/rest/restservices/IngredienteRestServiceTest.java
> +        assertEquals(expectedIngredienteList.size(),actualList.size());
👍

2019-10-01 01:00 UTC, vampymcr23 commented on src/test/java/com/tortu/api/rest/restservices/IngredienteRestServiceTest.java
> +        Mockito.verify(resourceMapper,Mockito.times(2)).map(Mockito.any(Ingrediente.class));
👍

2019-10-01 01:00 UTC, vampymcr23 commented on src/test/java/com/tortu/api/rest/restservices/RecetaRestServiceTest.java
> +        Mockito.doThrow(GeneralException.class).when(recetaService).saveReceta(receta);
💯

2019-10-01 01:00 UTC, vampymcr23 commented on src/test/java/com/tortu/api/rest/restservices/RecetaRestServiceTest.java
> +        Mockito.doThrow(GeneralException.class).when(recetaService).updateReceta(receta);
💯

2019-10-01 01:00 UTC, vampymcr23 commented on src/test/java/com/tortu/api/rest/restservices/RecetaRestServiceTest.java
> +        Mockito.doThrow(GeneralException.class).when(recetaService).deleteReceta(idReceta);
💯

2019-10-01 01:00 UTC, vampymcr23 commented on src/test/java/com/tortu/api/rest/restservices/UsuarioLayoutRestServiceTest.java
> +        assertTrue(response.getEntity() instanceof List);
Te falto comparar si la lista tiene 2 elementos.

2019-10-01 19:37 UTC, ginamerla commented
Terminado!

2019-10-02 15:57 UTC, vampymcr23 approved these changes
Listo! Aprobado.

2019-10-02 15:57 UTC, vampymcr23 commented on src/main/java/com/tortu/api/rest/mappers/IngredienteResourceMapper.java
> + * Implementacion del convertidor que mapea las propiedades de Ingrediente con el recurso para la capa REST
👍

2019-10-02 15:57 UTC, vampymcr23 commented on src/test/java/com/tortu/api/rest/restservices/UsuarioLayoutRestServiceTest.java
> +        assertEquals(2,responseList.size());
👍

2019-10-02 15:59 UTC, merged